// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALrF4UxCbgrCQafyfjsalTBr-1jpnS3tA',
    appId: '1:243698285888:web:24edc9ab8f256e58700ea5',
    messagingSenderId: '243698285888',
    projectId: 'chat-513aa',
    authDomain: 'chat-513aa.firebaseapp.com',
    storageBucket: 'chat-513aa.firebasestorage.app',
    measurementId: 'G-7NY9R3Q537',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALsUUz6hG4-0LNilsmb8GACIXCssrDJzg',
    appId: '1:243698285888:android:ec27a98c7c88b409700ea5',
    messagingSenderId: '243698285888',
    projectId: 'chat-513aa',
    storageBucket: 'chat-513aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOxGVk7yOi28umoX3J0E-F31eBUmRRb_8',
    appId: '1:243698285888:ios:a92b3bab4705f0f8700ea5',
    messagingSenderId: '243698285888',
    projectId: 'chat-513aa',
    storageBucket: 'chat-513aa.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOxGVk7yOi28umoX3J0E-F31eBUmRRb_8',
    appId: '1:243698285888:ios:a92b3bab4705f0f8700ea5',
    messagingSenderId: '243698285888',
    projectId: 'chat-513aa',
    storageBucket: 'chat-513aa.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALrF4UxCbgrCQafyfjsalTBr-1jpnS3tA',
    appId: '1:243698285888:web:dd05d33d2e779000700ea5',
    messagingSenderId: '243698285888',
    projectId: 'chat-513aa',
    authDomain: 'chat-513aa.firebaseapp.com',
    storageBucket: 'chat-513aa.firebasestorage.app',
    measurementId: 'G-3GD2CMH7RP',
  );

}